### ISSUE TITLE
Update Globe Content

### ISSUE THREAD

**Issue by iancrowther** [nodeschool/international-day#53]
Can we update the globe with new enrolment data?

London is missing :-)

**Comment by max-mapper** [comment]
btw, if [this](https://github.com/nodeschool/international-day/tree/2015/enrollment-scraper) was on a `gh-pages` branch we could just link to it directly from the globe site, but because it's in a branch called `2015` there isnt a CORS friendly link. But I figure in a couple of weeks this won't matter anymore so I haven't been too concerned about it

**Comment by iancrowther** [comment]
Is a good point. The 2015 branch was just an idea

**Comment by iancrowther** [comment]
next year :-)
