### ISSUE TITLE
2016 Preparation tasks

### ISSUE THREAD

**Issue by martinheidegger** [nodeschool/international-day#98]
- [x] Decide on a date: 2016-05-21
- [x] Create international-day github team with members: @iancrowther @martinheidegger and the other organizers that can push to the international-day repo
- [ ] Define responsibilities of main organizers
- [ ] Define responsibilities of chapter organizers
- [x] Setup registration google docs form for chapter organizers
- [x] Create stats google docs form to keep track of stats during the event
- [x] Setup video communication tool (https://appear.in/ ? )
- [x] Create new homepage with registration form for chapter organzers
- [ ] Prepare set of suggestions of what to do at the international day - **in-progress**
- [x] Last years video - **in-progress**
- [ ] ~~Setup rules for sponsorship~~

**Comment by martinheidegger** [comment]
@nodeschool/core Could someone help with the second task. I am (still?) not core

**Comment by iancrowther** [comment]
@martinheidegger date is out in task 1 😉

21st not the 16th

**Comment by iancrowther** [comment]
Yep task 2 is blocked! I have a 2016 branch started

**Comment by iancrowther** [comment]
Good list btw

**Comment by SomeoneWeird** [comment]
Done number 2. You should be able to add people to it using the bot

**Comment by iancrowther** [comment]
I dont seem to have admin rights on this room - appear.in/nodeschool, who is the listed owner?

**Comment by iancrowther** [comment]
added last years vid to the list

**Comment by martinheidegger** [comment]
I am the owner of appear.in/nodeschool and I have not yet figured out how to give others ownership :stuck_out_tongue:

**Comment by iancrowther** [comment]
ah thats ok then, for some reason I thought it was something that got handed around chapters and was lost.

**Comment by rickheere** [comment]
Any progression on this one? NodeSchool Haarlem would like to participate on next years edition. 
edit: typo

**Comment by iancrowther** [comment]
updated https://github.com/nodeschool/international-day/issues/96 by mistake

**Comment by iancrowther** [comment]
ok video is now underway..!

**Comment by Sequoia** [comment]
:-1: "rules for sponsorship" unless someone's gonna make a nodeschool international day org, trademark the name, set up governance model etc. and actually enforce the rules. Otherwise the rules are both arbitrary (who sets the rules? how? I certainly don't want to be in charge of answering these questions...) and unenforceable.

## proposal
Explain the ✨Spirit of Nodeschool✨ and write *recommendations* for sponsorship for people to stay in keeping with "nodeschool culture"/accessibility/sharing/etc..

I can take a swing at writing such a thing if ppl like that idea.

**Comment by Sequoia** [comment]
Alternately the Lords of Nodeschool could write sponsorship requirements *to be included in official event listings*. That way it's still opt-in & ppl can make their own choice about how important it is to them to be in main event listing. Even that seems like a hassle tho, and equally arbitrary without some sort of formal/democratic process.

I think I've talked myself back into the "guidelines only" camp 😋

**Comment by Sequoia** [comment]
Discussion of sponsorship rules: #99

**Comment by a0viedo** [comment]
what about website modifications and enrollment?

**Comment by Sequoia** [comment]
In order to have "rules" Nodeschool would need a clear process for creating rules and a mechanism to enforce them. As a "community" rather than an "organization," Nodeschool has neither, so any rules would effectively be arbitrary & toothless. I've struck "sponsorship rules" from the to do list in light of this.

_Side note: without a clear decision making process, mission statement, governing committee etc., discussions of rules like this are confusing, contentious, and ultimately meaningless; in short, a waste of time. See: #99_

**Comment by iancrowther** [comment]
@Sequoia agreed

**Comment by iancrowther** [comment]
@martinheidegger @Sequoia @a0viedo I have created the first cut of the enrolment form.

https://docs.google.com/a/nexttick.io/forms/d/13Kft4DVlrLgr0lsnhVGNgjV3CZJDkfsNysKxdeHPTFs/edit?usp=sharing

Please feedback, am I missing anything?

**Comment by iancrowther** [comment]
@martinheidegger what needs to be done for appear.in? thats ready to go right?

**Comment by iancrowther** [comment]
@martinheidegger @Sequoia @a0viedo I have created the first cut of the stats feedback form 

http://goo.gl/forms/Dn1eL9XhTo

Please feedback and edit as apropriate

**Comment by iancrowther** [comment]
"Define responsibilities of main organizers" - this is a good call.

can we add noted to this playbook? https://github.com/nodeschool/international-day/blob/2016/ORGANISERS.md

**Comment by tdd** [comment]
Hey Ian,

Apparently you're in charge of my TZ range already (+2 DST on that date), so do I need to put anything in (Paris chapter here)?

**Comment by iancrowther** [comment]
Ideally we have a couple of people for each timezone, your input would be most welcome

**Comment by tdd** [comment]
Hey Ian,

OK so added my contact info for GMT+0/1/2.

**Comment by iancrowther** [comment]
great, can you add your thoughts regarding organiser reponsibilities?

eg. what do you expect to be doing as a timezone champion

**Comment by thebergamo** [comment]
where can I see the organizers responsabilities?
In this year, need to create more chapters in SP hehe

**Comment by iancrowther** [comment]
@thebergamo - individual chapter organisers should read:

https://github.com/nodeschool/international-day/blob/2016/PARTICIPATING.md

whilst timezone champions should read:

https://github.com/nodeschool/international-day/blob/2016/ORGANISERS.md

We need to add some details to the organisers.md still as per the checkbox "Define responsibilities of chapter organizers".  feel free to chip in

**Comment by iancrowther** [comment]
"Prepare set of suggestions of what to do at the international day" - in-progress - https://github.com/nodeschool/international-day/issues/108

**Comment by thebergamo** [comment]
@iancrowther thanks!
Maybe I can help in UTC -03:00 (São Paulo)

**Comment by iancrowther** [comment]
submit a PR and get onboard :-)

**Comment by iancrowther** [comment]
@thebergamo - I updated the readme the be a bit more explicit, can you review to see if it makes sense?

https://github.com/nodeschool/international-day/blob/2016/README.md

**Comment by tdd** [comment]
> great, can you add your thoughts regarding organiser reponsibilities?
> 
> eg. what do you expect to be doing as a timezone champion

Hey @iancrowther I'll provide 2015 feedback in #108 then add expectations for 2016 here.

**Comment by tdd** [comment]
OK as for 2015 feedback and suggestions, [here it is](https://github.com/nodeschool/international-day/issues/108#issuecomment-168379101).

Now for 2016. Two sides here: as a chapter organizer, and as a TZ "champion".

# As the Paris chapter organizer

[NodeSchool Paris](http://www.meetup.com/NodeSchool-Paris/) always runs for a full Saturday at Mozilla Paris' gorgeous Salle des Fêtes ([see photos](http://www.meetup.com/fr/NodeSchool-Paris/photos/)). This is a seating-at-tables, fully-catered event running from 10am to 6pm. We host 60 people including up to 6 mentors, giving us a 1/9 mentor/attendee ratio. Sessions are sponsored by my company, by Mozilla and up to 2 other ones. NID 2016 would likely be our 9th session (we go about every 7 weeks, except during Summer / early Fall).

People are introduced to what NodeSchool is, how to install Node, install a workshop, run it, work through a challenge and mark it as solved, etc. We use 6 9-person tables and try to arrange them in a blend of total noobs (no JS ever, or at least no Node ever) and more seasoned people, and ask them then to do rounds of intros within tables, to help get things going. We also introduce all the mentors and all the workshops. People can tackle whatever they want, however they want.

The general schedule is:
- 10:00-10:30 = breakfast
- 10:30-10:45 = intro, getting started, demos, grouping by interests
- 10:30-12:15 = first streak
- 12:15-12:30 = first round of commented live solutions for popular challenges
- 12:30-13:30 = lunch
- 13:30-17:30 = second streak
- 17:30-17:50 = second round of commented live solutions for popular challenges
- 17:50-18:00 = wrap-up

This year I'd love to coordinate AOT with other chapters in our TZ and neighboring ones so we can prepare cool interactions between them and us throughout the day.  Perhaps contests, or just videoconferencing, or whatever. Just loosely tie the chapters together for a day, making it truly "international", instead of just all-on-same-day.

# As a TZ "champion" across UTC -> UTC+2

I wonder what a TZ champion's duties would be. Act as a coordination point between chapters in the TZ, I guess, something along these lines:
- Know each chapter owner (met them online or IRL)
- Have had discussions with each AOT, to be aware of what they're up to
- Be available through SMS / Twitter / whatever throughout the TZ's "business hours"
- Grease the wheels during the day for planned cross-chapter interactions (perhaps ping the relevant chapter owners with reminders a few minutes before, stuff like that)

JM2C!

**Comment by thebergamo** [comment]
@iancrowther why instead nodeschool-int (confused) we not using nodeschool-day as #hashtag?

**Comment by iancrowther** [comment]
@thebergamo When I was researching for media for the film, I searched twitter for the hashtag #international-day and it turns out there are a lot of other orgs that use that hashtag.

using #nodeschool-int is unique

**Comment by thebergamo** [comment]
@iancrowther I not suggest #international-day, suggest **#nodeschool-day**

**Comment by iancrowther** [comment]
Lol - good point!!

**Comment by iancrowther** [comment]
Both work for me, anyone else have an opinion?

**Comment by thebergamo** [comment]
:p me too! Is better discuss in PR not?

**Comment by iancrowther** [comment]
https://github.com/nodeschool/international-day/pull/115

**Comment by iancrowther** [comment]
Great job folks
